// Service-area (location) pages. Each generates /service-areas/<slug>.
// Every entry has a county + real local landmarks/roads so each page has
// genuinely unique content (better local SEO, avoids thin/duplicate pages).

export const areas = [
  // ---- Core Greater Houston metro ----
  { slug: 'houston', name: 'Houston', county: 'Harris County', blurb: 'Our home base — full-service signage across the city of Houston.',
    landmarks: ['Downtown Houston', 'The Galleria', 'the Energy Corridor', 'the Texas Medical Center', 'I-10 & Beltway 8'] },
  { slug: 'katy', name: 'Katy', county: 'Harris & Fort Bend County', blurb: 'Custom signs, wraps, and graphics for Katy businesses.',
    landmarks: ['Katy Mills', 'Cinco Ranch', 'Old Katy', 'I-10 & the Grand Parkway (99)'] },
  { slug: 'cypress', name: 'Cypress', county: 'Harris County', blurb: 'Signage and vehicle wraps serving the Cypress area.',
    landmarks: ['Towne Lake', 'Bridgeland', 'Houston Premium Outlets', 'US-290 & the Grand Parkway'] },
  { slug: 'sugar-land', name: 'Sugar Land', county: 'Fort Bend County', blurb: 'Professional signs and wraps for Sugar Land companies.',
    landmarks: ['Sugar Land Town Square', 'First Colony Mall', 'Smart Financial Centre', 'US-59 / I-69'] },
  { slug: 'spring', name: 'Spring', county: 'Harris County', blurb: 'Indoor, outdoor, and vehicle signage in Spring, TX.',
    landmarks: ['Old Town Spring', 'the ExxonMobil campus', 'I-45 & the Grand Parkway'] },
  { slug: 'the-woodlands', name: 'The Woodlands', county: 'Montgomery County', blurb: 'High-quality signage for The Woodlands businesses.',
    landmarks: ['The Woodlands Mall', 'Market Street', 'Cynthia Woods Mitchell Pavilion', 'I-45'] },
  { slug: 'pearland', name: 'Pearland', county: 'Brazoria County', blurb: 'Storefront signs, wraps, and graphics in Pearland.',
    landmarks: ['Pearland Town Center', 'TX-288', 'Beltway 8'] },
  { slug: 'pasadena', name: 'Pasadena', county: 'Harris County', blurb: 'Complete sign services for Pasadena, TX.',
    landmarks: ['Pasadena Town Square', 'TX-225', 'the Ship Channel industrial district'] },
  { slug: 'bellaire', name: 'Bellaire', county: 'Harris County', blurb: 'Custom business signage throughout Bellaire.',
    landmarks: ['the "City of Homes" district', 'Bellaire Boulevard', 'the nearby Galleria'] },
  { slug: 'stafford', name: 'Stafford', county: 'Fort Bend County', blurb: 'Signs and vehicle wraps serving Stafford.',
    landmarks: ['the Stafford Centre', 'US-90 Alt', 'the Texas 90 business corridor'] },
  { slug: 'missouri-city', name: 'Missouri City', county: 'Fort Bend County', blurb: 'Branding and signage for Missouri City businesses.',
    landmarks: ['Sienna', 'Fort Bend Town Center', 'TX-6'] },
  { slug: 'richmond', name: 'Richmond', county: 'Fort Bend County', blurb: 'Full-service sign company serving Richmond, TX.',
    landmarks: ['historic downtown Richmond', 'the Brazos River', 'US-59 / I-69'] },
  { slug: 'rosenberg', name: 'Rosenberg', county: 'Fort Bend County', blurb: 'Custom signs and graphics in Rosenberg.',
    landmarks: ['historic downtown Rosenberg', 'US-59 & TX-36', 'Brazos Town Center'] },
  { slug: 'humble', name: 'Humble', county: 'Harris County', blurb: 'Indoor and outdoor signage for Humble, TX.',
    landmarks: ['Deerbrook Mall', 'Bush Intercontinental Airport (IAH)', 'US-59'] },
  { slug: 'tomball', name: 'Tomball', county: 'Harris County', blurb: 'Signs, banners, and wraps serving Tomball.',
    landmarks: ['Old Town Tomball', 'TX-249 (the Tomball Tollway)', 'the German Heritage district'] },
  { slug: 'conroe', name: 'Conroe', county: 'Montgomery County', blurb: 'Professional signage for Conroe businesses.',
    landmarks: ['Lake Conroe', 'historic downtown Conroe', 'I-45'] },
  { slug: 'league-city', name: 'League City', county: 'Galveston County', blurb: 'Custom signs and vehicle wraps in League City.',
    landmarks: ['South Shore Harbour', 'the Clear Lake area', 'I-45'] },
  { slug: 'friendswood', name: 'Friendswood', county: 'Galveston & Harris County', blurb: 'Business signage and graphics for Friendswood.',
    landmarks: ['FM 518', 'Clear Creek', 'the Baybrook area'] },
  { slug: 'baytown', name: 'Baytown', county: 'Harris County', blurb: 'Full-service sign company serving Baytown, TX.',
    landmarks: ['San Jacinto Mall', 'TX-146', 'the Bayway industrial corridor'] },
  { slug: 'channelview', name: 'Channelview', county: 'Harris County', blurb: 'Signs, wraps, and graphics in Channelview.',
    landmarks: ['I-10 East', 'the San Jacinto River', 'the Houston Ship Channel'] },
  { slug: 'alief', name: 'Alief', county: 'Harris County', blurb: 'Local signage and wraps for the Alief area.',
    landmarks: ['Bellaire Boulevard', 'Beltway 8', 'southwest Houston'] },
  { slug: 'jersey-village', name: 'Jersey Village', county: 'Harris County', blurb: 'Custom business signs in Jersey Village.',
    landmarks: ['US-290', 'northwest Houston', 'the US-290 retail corridor'] },
  { slug: 'galena-park', name: 'Galena Park', county: 'Harris County', blurb: 'Signage and vehicle graphics for Galena Park.',
    landmarks: ['the Houston Ship Channel', 'Clinton Drive', 'the East End'] },
  { slug: 'deer-park', name: 'Deer Park', county: 'Harris County', blurb: 'Complete sign services serving Deer Park, TX.',
    landmarks: ['the San Jacinto Monument', 'TX-225', '"the Birthplace of Texas"'] },

  // ---- West Houston / Fort Bend & Waller County ----
  { slug: 'cinco-ranch', name: 'Cinco Ranch', county: 'Fort Bend County', blurb: 'Storefront and business signage for Cinco Ranch.',
    landmarks: ['the Cinco Ranch master-planned community', 'the Grand Parkway (99)', 'LaCenterra at Cinco Ranch'] },
  { slug: 'fulshear', name: 'Fulshear', county: 'Fort Bend County', blurb: 'Custom signs and wraps for growing Fulshear businesses.',
    landmarks: ['Cross Creek Ranch', 'FM 1093', 'historic downtown Fulshear'] },
  { slug: 'mission-bend', name: 'Mission Bend', county: 'Fort Bend & Harris County', blurb: 'Signage and graphics serving the Mission Bend area.',
    landmarks: ['US-59', 'Bellaire Boulevard', 'southwest Houston'] },
  { slug: 'barker', name: 'Barker', county: 'Harris County', blurb: 'Business signs and vehicle wraps in Barker, TX.',
    landmarks: ['the Barker Reservoir', 'I-10 West', 'the Energy Corridor'] },
  { slug: 'brookshire', name: 'Brookshire', county: 'Waller County', blurb: 'Full-service signage for Brookshire businesses.',
    landmarks: ['I-10', 'the Igloo campus', 'Polo Ranch'] },
  { slug: 'pattison', name: 'Pattison', county: 'Waller County', blurb: 'Custom signs and graphics serving Pattison, TX.',
    landmarks: ['I-10', 'the FM 359 corridor', 'nearby Brookshire'] },
  { slug: 'simonton', name: 'Simonton', county: 'Fort Bend County', blurb: 'Signage and wraps for the Simonton community.',
    landmarks: ['the Brazos River', 'FM 1093', 'the Fulshear–Simonton area'] },
  { slug: 'san-felipe', name: 'San Felipe', county: 'Austin County', blurb: 'Signs, banners, and graphics in San Felipe, TX.',
    landmarks: ['the Stephen F. Austin colony historic site', 'the Brazos River', 'I-10'] },
  { slug: 'sealy', name: 'Sealy', county: 'Austin County', blurb: 'Complete sign services for Sealy businesses.',
    landmarks: ['I-10 & TX-36', 'historic downtown Sealy', 'Stephen F. Austin State Park'] },
  { slug: 'waller', name: 'Waller', county: 'Waller & Harris County', blurb: 'Custom signage and vehicle wraps in Waller, TX.',
    landmarks: ['US-290', 'the FM 362 corridor', 'the Daikin Texas campus'] },
  { slug: 'hockley', name: 'Hockley', county: 'Harris County', blurb: 'Indoor and outdoor signs serving Hockley, TX.',
    landmarks: ['US-290', 'Houston Premium Outlets', 'the Daikin campus'] },
  { slug: 'prairie-view', name: 'Prairie View', county: 'Waller County', blurb: 'Business and campus signage for Prairie View.',
    landmarks: ['Prairie View A&M University', 'US-290', 'the FM 1098 corridor'] },
  { slug: 'hempstead', name: 'Hempstead', county: 'Waller County', blurb: 'Full-service sign company serving Hempstead, TX.',
    landmarks: ['US-290 & TX-6', 'historic downtown Hempstead', 'the "Watermelon Capital" district'] },

  // ---- Brazos Valley & Austin County ----
  { slug: 'brenham', name: 'Brenham', county: 'Washington County', blurb: 'Custom signs, wraps, and graphics for Brenham businesses.',
    landmarks: ['Blue Bell Creameries', 'historic downtown Brenham', 'US-290', 'the antique & wine district'] },
  { slug: 'bellville', name: 'Bellville', county: 'Austin County', blurb: 'Signage and vehicle graphics serving Bellville, TX.',
    landmarks: ['the historic courthouse square', 'TX-36', 'the Austin County Fairgrounds'] },
  { slug: 'chappell-hill', name: 'Chappell Hill', county: 'Washington County', blurb: 'Business signage for the Chappell Hill area.',
    landmarks: ['the Chappell Hill Historic District', 'US-290', 'the bluebonnet & sausage festivals'] },
  { slug: 'cat-spring', name: 'Cat Spring', county: 'Austin County', blurb: 'Custom signs and graphics serving Cat Spring, TX.',
    landmarks: ['the Cat Spring Agricultural Society hall', 'FM 949', 'the rural Austin County countryside'] },
  { slug: 'industry', name: 'Industry', county: 'Austin County', blurb: 'Signs and wraps for businesses in Industry, TX.',
    landmarks: ['the oldest German settlement in Texas', 'TX-159', 'downtown Industry'] },
  { slug: 'new-ulm', name: 'New Ulm', county: 'Austin County', blurb: 'Signage and graphics serving New Ulm, TX.',
    landmarks: ['the rolling hills of Austin County', 'area wineries', 'FM 109'] },
  { slug: 'kenney', name: 'Kenney', county: 'Austin County', blurb: 'Custom business signs in Kenney, TX.',
    landmarks: ['the historic Kenney Store', 'FM 1456', 'the Brenham–Bellville area'] },
  { slug: 'bleiblerville', name: 'Bleiblerville', county: 'Austin County', blurb: 'Signage and wraps for the Bleiblerville community.',
    landmarks: ['the rural farming community', 'FM 2502', 'northern Austin County'] },
  { slug: 'eagle-lake', name: 'Eagle Lake', county: 'Colorado County', blurb: 'Full-service signs and graphics for Eagle Lake, TX.',
    landmarks: ['the "Goose Hunting Capital of the World"', 'US-90 Alt', 'historic downtown Eagle Lake'] },

  // ---- Major Texas metros (factory-direct — we manufacture in Houston and ship/serve statewide) ----
  { slug: 'dallas', name: 'Dallas', county: 'Dallas County', blurb: 'Factory-direct custom signs manufactured in Houston and delivered to Dallas businesses.',
    landmarks: ['Downtown Dallas', 'the I-635 / I-35E corridors', 'Uptown & Deep Ellum'] },
  { slug: 'fort-worth', name: 'Fort Worth', county: 'Tarrant County', blurb: 'Custom signs and graphics for Fort Worth businesses, built factory-direct.',
    landmarks: ['Downtown Fort Worth', 'the Stockyards', 'I-35W'] },
  { slug: 'austin', name: 'Austin', county: 'Travis County', blurb: 'Factory-direct signage for Austin businesses — manufactured in Houston, delivered to you.',
    landmarks: ['Downtown Austin', 'the I-35 corridor', 'the Domain'] },
  { slug: 'san-antonio', name: 'San Antonio', county: 'Bexar County', blurb: 'Custom signs and wraps for San Antonio businesses, built factory-direct.',
    landmarks: ['Downtown San Antonio', 'the I-10 / Loop 410 corridors', 'the Pearl District'] },
  { slug: 'corpus-christi', name: 'Corpus Christi', county: 'Nueces County', blurb: 'Factory-direct signage delivered to Corpus Christi businesses.',
    landmarks: ['Downtown Corpus Christi', 'SPID (TX-358)', 'the bayfront'] },
  { slug: 'el-paso', name: 'El Paso', county: 'El Paso County', blurb: 'Custom signs manufactured in Houston and shipped to El Paso businesses.',
    landmarks: ['Downtown El Paso', 'the I-10 corridor', 'the Westside'] },
];

export const getArea = (slug) => areas.find((a) => a.slug === slug);
export const areaIndex = (slug) => areas.findIndex((a) => a.slug === slug);
